name: Random Hash Check

on: [push, pull_request]

jobs:
  test_hash:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: pip install hashlib

      - name: Ejecutar script
        run: python random_hash.py
